# Generated by cpp11: do not edit by hand

fillDown <- function(x) {
    force(x)
  .Call(`_tidyr_fillDown`, x)
}

fillUp <- function(x) {
    force(x)
  .Call(`_tidyr_fillUp`, x)
}

melt_dataframe <- function(data, id_ind, measure_ind, variable_name, value_name, attrTemplate, factorsAsStrings, valueAsFactor, variableAsFactor) {
    force(data)
    force(id_ind)
    force(measure_ind)
    force(variable_name)
    force(value_name)
    force(attrTemplate)
    force(factorsAsStrings)
    force(valueAsFactor)
    force(variableAsFactor)
  .Call(`_tidyr_melt_dataframe`, data, id_ind, measure_ind, variable_name, value_name, attrTemplate, factorsAsStrings, valueAsFactor, variableAsFactor)
}

simplifyPieces <- function(pieces, p, fillLeft) {
    force(pieces)
    force(p)
    force(fillLeft)
  .Call(`_tidyr_simplifyPieces`, pieces, p, fillLeft)
}
